/* ============================================================
   mock-data.js — seed registrations for admin sandbox testing
   Replace with a Supabase fetch post-migration.
   Dates are anchored relative to "now" at module load so the admin
   page always shows a believable mix of fresh/expiring/expired rows.
   ============================================================ */

const now = Date.now();
const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

function iso(offsetMs) {
  return new Date(now + offsetMs).toISOString();
}

export const MOCK_REGISTRATIONS = [
  {
    id: 'mock-001',
    full_name: 'Dr. Ayşe Yılmaz',
    email: 'ayse.yilmaz@example.com',
    phone: '+90 532 111 22 33',
    specialty: 'ftr',
    position: 'uzman',
    institution: 'İstanbul Üniversitesi Cerrahpaşa',
    notes: '',
    status: 'pending',
    registered_at: iso(-3 * HOUR),
    expires_at: iso(45 * HOUR),
    confirmed_at: null,
    confirmed_by: null,
    cancelled_at: null,
    cancellation_reason: null,
    payment_reference: null,
  },
  {
    id: 'mock-002',
    full_name: 'Dr. Mehmet Kaya',
    email: 'mehmet.kaya@hospital.com.tr',
    phone: '+90 505 444 55 66',
    specialty: 'ortopedi',
    position: 'uzman',
    institution: 'Acıbadem Maslak Hastanesi',
    notes: 'Fatura için kurum bilgilerini kullanmak istiyorum.',
    status: 'pending',
    registered_at: iso(-30 * HOUR),
    expires_at: iso(18 * HOUR),
    confirmed_at: null,
    confirmed_by: null,
    cancelled_at: null,
    cancellation_reason: null,
    payment_reference: null,
  },
  {
    id: 'mock-003',
    full_name: 'Dr. Zeynep Demir',
    email: 'zeynep.demir@example.org',
    phone: '+90 533 777 88 99',
    specialty: 'spor_hekimligi',
    position: 'uzman',
    institution: 'Hacettepe Üniversitesi Tıp Fakültesi',
    notes: '',
    status: 'confirmed',
    registered_at: iso(-5 * DAY),
    expires_at: iso(-3 * DAY),
    confirmed_at: iso(-3 * DAY - 2 * HOUR),
    confirmed_by: 'kayit@sonoinjection.com',
    cancelled_at: null,
    cancellation_reason: null,
    payment_reference: 'TR-INV-2026-0042',
  },
  {
    id: 'mock-004',
    full_name: 'Dr. Can Öztürk',
    email: 'can.ozturk@example.com',
    phone: '+49 175 1234567',
    specialty: 'romatoloji',
    position: 'asistan',
    institution: 'Charité — Universitätsmedizin Berlin',
    notes: 'Vegetaryen menü tercih ederim.',
    status: 'confirmed',
    registered_at: iso(-7 * DAY),
    expires_at: iso(-5 * DAY),
    confirmed_at: iso(-4 * DAY),
    confirmed_by: 'info@sonoinjection.com',
    cancelled_at: null,
    cancellation_reason: null,
    payment_reference: 'TR-INV-2026-0039',
  },
  {
    id: 'mock-005',
    full_name: 'Dr. Selin Aksoy',
    email: 'selin.aksoy@example.com',
    phone: '+90 545 222 33 44',
    specialty: 'algoloji',
    position: 'uzman',
    institution: 'Marmara Üniversitesi Pendik EAH',
    notes: '',
    status: 'expired',
    registered_at: iso(-10 * DAY),
    expires_at: iso(-8 * DAY),
    confirmed_at: null,
    confirmed_by: null,
    cancelled_at: null,
    cancellation_reason: null,
    payment_reference: null,
  },
  {
    id: 'mock-006',
    full_name: 'Dr. Burak Tekin',
    email: 'burak.tekin@example.com',
    phone: '+90 530 999 00 11',
    specialty: 'ftr',
    position: 'asistan',
    institution: 'Ankara Üniversitesi Tıp Fakültesi',
    notes: '',
    status: 'cancelled',
    registered_at: iso(-12 * DAY),
    expires_at: iso(-10 * DAY),
    confirmed_at: null,
    confirmed_by: null,
    cancelled_at: iso(-11 * DAY),
    cancellation_reason: 'Katılımcının kendi talebi üzerine iptal edildi.',
    payment_reference: null,
  },
  {
    id: 'mock-007',
    full_name: 'Dr. Elif Çelik',
    email: 'elif.celik@example.com',
    phone: '+90 542 555 11 22',
    specialty: 'diger',
    position: 'uzman',
    institution: 'Özel Klinik — Bağımsız',
    notes: 'Eğitim materyallerine erken erişim talep ediyorum.',
    status: 'pending',
    registered_at: iso(-1 * HOUR),
    expires_at: iso(47 * HOUR),
    confirmed_at: null,
    confirmed_by: null,
    cancelled_at: null,
    cancellation_reason: null,
    payment_reference: null,
  },
];
